"""add tax_rates table

Revision ID: 71db5c2b547a
Revises: 001
Create Date: 2026-04-11 04:07:48.815428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71db5c2b547a'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tax_rates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("county", sa.String(), nullable=False),
        sa.Column("rate", sa.Float(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.text("true")),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tax_rates_county"), "tax_rates", ["county"], unique=True)
    op.create_index(op.f("ix_tax_rates_id"), "tax_rates", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tax_rates_id"), table_name="tax_rates")
    op.drop_index(op.f("ix_tax_rates_county"), table_name="tax_rates")
    op.drop_table("tax_rates")
    # ### end Alembic commands ###
