"""add_index_projects_created_by

Revision ID: c81ad061b618
Revises: 52f8ce334bc7
Create Date: 2026-06-04 23:52:25.270184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c81ad061b618'
down_revision: Union[str, None] = '52f8ce334bc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blueprint_detection_feedback_detection_id'), table_name='blueprint_detection_feedback')
    op.alter_column('blueprint_detections', 'needs_review',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('chat_attachments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_chat_attachments_id'), 'chat_attachments', ['id'], unique=False)
    op.alter_column('estimate_actuals', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('estimate_actuals', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('estimate_actuals_estimate_id_key'), 'estimate_actuals', type_='unique')
    op.drop_index(op.f('ix_estimate_actuals_estimate_id'), table_name='estimate_actuals')
    op.create_index(op.f('ix_estimate_actuals_estimate_id'), 'estimate_actuals', ['estimate_id'], unique=True)
    op.create_index(op.f('ix_estimate_actuals_id'), 'estimate_actuals', ['id'], unique=False)
    op.create_index(op.f('ix_estimate_actuals_organization_id'), 'estimate_actuals', ['organization_id'], unique=False)
    op.alter_column('estimates', 'market_adjustment_applied',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('1.0'))
    op.alter_column('estimates', 'agent_trace',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::json"))
    op.alter_column('estimates', 'confidence_components',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::json"))
    op.alter_column('job_cost_entries', 'occurred_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('job_cost_entries', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_job_cost_entries_id'), 'job_cost_entries', ['id'], unique=False)
    op.create_index(op.f('ix_job_cost_entries_organization_id'), 'job_cost_entries', ['organization_id'], unique=False)
    op.create_index(op.f('ix_photos_id'), 'photos', ['id'], unique=False)
    op.create_index(op.f('ix_projects_created_by'), 'projects', ['created_by'], unique=False)
    op.create_index(op.f('ix_public_agent_audits_id'), 'public_agent_audits', ['id'], unique=False)
    op.drop_index(op.f('ix_vision_mappings_item_type'), table_name='vision_item_mappings')
    op.drop_index(op.f('ix_vision_mappings_org'), table_name='vision_item_mappings')
    op.drop_constraint(op.f('vision_item_mappings_item_type_key'), 'vision_item_mappings', type_='unique')
    op.create_index(op.f('ix_vision_item_mappings_id'), 'vision_item_mappings', ['id'], unique=False)
    op.create_index(op.f('ix_vision_item_mappings_item_type'), 'vision_item_mappings', ['item_type'], unique=True)
    op.create_index(op.f('ix_vision_item_mappings_organization_id'), 'vision_item_mappings', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vision_item_mappings_organization_id'), table_name='vision_item_mappings')
    op.drop_index(op.f('ix_vision_item_mappings_item_type'), table_name='vision_item_mappings')
    op.drop_index(op.f('ix_vision_item_mappings_id'), table_name='vision_item_mappings')
    op.create_unique_constraint(op.f('vision_item_mappings_item_type_key'), 'vision_item_mappings', ['item_type'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_vision_mappings_org'), 'vision_item_mappings', ['organization_id'], unique=False)
    op.create_index(op.f('ix_vision_mappings_item_type'), 'vision_item_mappings', ['item_type'], unique=True)
    op.drop_index(op.f('ix_public_agent_audits_id'), table_name='public_agent_audits')
    op.drop_index(op.f('ix_projects_created_by'), table_name='projects')
    op.drop_index(op.f('ix_photos_id'), table_name='photos')
    op.drop_index(op.f('ix_job_cost_entries_organization_id'), table_name='job_cost_entries')
    op.drop_index(op.f('ix_job_cost_entries_id'), table_name='job_cost_entries')
    op.alter_column('job_cost_entries', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('job_cost_entries', 'occurred_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('estimates', 'confidence_components',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::json"))
    op.alter_column('estimates', 'agent_trace',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::json"))
    op.alter_column('estimates', 'market_adjustment_applied',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('1.0'))
    op.drop_index(op.f('ix_estimate_actuals_organization_id'), table_name='estimate_actuals')
    op.drop_index(op.f('ix_estimate_actuals_id'), table_name='estimate_actuals')
    op.drop_index(op.f('ix_estimate_actuals_estimate_id'), table_name='estimate_actuals')
    op.create_index(op.f('ix_estimate_actuals_estimate_id'), 'estimate_actuals', ['estimate_id'], unique=False)
    op.create_unique_constraint(op.f('estimate_actuals_estimate_id_key'), 'estimate_actuals', ['estimate_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('estimate_actuals', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('estimate_actuals', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_chat_attachments_id'), table_name='chat_attachments')
    op.alter_column('chat_attachments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('blueprint_detections', 'needs_review',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_blueprint_detection_feedback_detection_id'), 'blueprint_detection_feedback', ['detection_id'], unique=False)
    # ### end Alembic commands ###
