"""agent_memories table for long-term agent memory

Revision ID: e4601e7c47d1
Revises: 07027b470d0d
Create Date: 2026-04-25 18:54:27.816689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'e4601e7c47d1'
down_revision: Union[str, None] = '07027b470d0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_memories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('source_session_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_referenced_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['source_session_id'], ['chat_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_memories_id'), 'agent_memories', ['id'], unique=False)
    op.create_index(op.f('ix_agent_memories_kind'), 'agent_memories', ['kind'], unique=False)
    op.create_index(op.f('ix_agent_memories_organization_id'), 'agent_memories', ['organization_id'], unique=False)
    op.create_index(op.f('ix_agent_memories_user_id'), 'agent_memories', ['user_id'], unique=False)
    op.create_index('ix_agent_memories_user_kind', 'agent_memories', ['user_id', 'kind'], unique=False)
    op.add_column('blueprint_jobs', sa.Column('original_filename', sa.String(length=500), nullable=True))
    op.create_unique_constraint('uq_blueprint_pages_job_page', 'blueprint_pages', ['job_id', 'page_number'])
    op.create_index('ix_line_items_estimate_sort_order', 'estimate_line_items', ['estimate_id', 'sort_order'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_line_items_estimate_sort_order', table_name='estimate_line_items')
    op.drop_constraint('uq_blueprint_pages_job_page', 'blueprint_pages', type_='unique')
    op.drop_column('blueprint_jobs', 'original_filename')
    op.drop_index('ix_agent_memories_user_kind', table_name='agent_memories')
    op.drop_index(op.f('ix_agent_memories_user_id'), table_name='agent_memories')
    op.drop_index(op.f('ix_agent_memories_organization_id'), table_name='agent_memories')
    op.drop_index(op.f('ix_agent_memories_kind'), table_name='agent_memories')
    op.drop_index(op.f('ix_agent_memories_id'), table_name='agent_memories')
    op.drop_table('agent_memories')
    # ### end Alembic commands ###
