"""Document generation router (Track D3).

Endpoints:
* POST /api/v1/estimates/{id}/docs/cover-letter
* POST /api/v1/estimates/{id}/docs/scope-of-work
* POST /api/v1/estimates/change-order             — body: {original_id, revised_id, reason?}

All endpoints return {"text": str, "source": "llm"|"static"} so the UI can
show a "draft generated by AI" badge and let the user edit before send.
"""
from __future__ import annotations

from typing import Optional

import structlog
from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.auth import get_current_user
from app.database import get_db
from app.models.estimates import Estimate
from app.models.users import User
from app.services.doc_generation import (
    generate_change_order,
    generate_cover_letter,
    generate_scope_of_work,
)

logger = structlog.get_logger()
router = APIRouter()


class CoverLetterBody(BaseModel):
    customer_name: Optional[str] = None


class ChangeOrderBody(BaseModel):
    original_id: int
    revised_id: int
    reason: Optional[str] = None


async def _load_org_estimate(
    db: AsyncSession, estimate_id: int, user: User
) -> Estimate:
    res = await db.execute(select(Estimate).where(Estimate.id == estimate_id))
    est: Optional[Estimate] = res.scalar_one_or_none()
    if not est:
        raise HTTPException(status_code=404, detail="Estimate not found")
    if est.organization_id and est.organization_id != getattr(user, "organization_id", None):
        raise HTTPException(status_code=403, detail="Forbidden")
    return est


@router.post("/{estimate_id}/docs/cover-letter")
async def cover_letter(
    estimate_id: int,
    body: CoverLetterBody = CoverLetterBody(),
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    est = await _load_org_estimate(db, estimate_id, current_user)
    return await generate_cover_letter(est, customer_name=body.customer_name)


@router.post("/{estimate_id}/docs/scope-of-work")
async def scope_of_work(
    estimate_id: int,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    est = await _load_org_estimate(db, estimate_id, current_user)
    return await generate_scope_of_work(est)


@router.post("/change-order")
async def change_order(
    body: ChangeOrderBody,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    if body.original_id == body.revised_id:
        raise HTTPException(status_code=400, detail="original_id and revised_id must differ")
    original = await _load_org_estimate(db, body.original_id, current_user)
    revised = await _load_org_estimate(db, body.revised_id, current_user)
    return await generate_change_order(original, revised, reason=body.reason)
